import React from 'react'

const TerminosDeUso = () => {
  return (
    <>
     <div style={{backgroundColor: 'gray', paddingTop: '5vw', paddingLeft: '8vw'}}>
       
      <b>Los tiempos de espera para la asistencia telefónica son más largos que lo habitual</b>
      <hr />
      
     <b>Los tiempos de espera para la asistencia por chat son más largos que lo habitual</b>
     <p style={{marginTop: '2px'}}>Vuelve a intentarlo más tarde o busca las respuestas en nuestro Centro de ayuda.</p>
     </div>
     <div style={{backgroundColor: 'white', paddingRight: '10vw', paddingLeft: '8vw'}}>
      <h1>Términos de uso de Netflix</h1>
      <p>Netflix brinda un servicio de membresía personalizado que permite a nuestros miembros acceder a contenido de entretenimiento (el «contenido de Netflix») a través de internet en ciertas TV, computadoras y otros dispositivos conectados a internet («dispositivos compatibles con Netflix»).</p>
      <p>El proveedor del servicio de Netflix es Netflix, Inc. Los presentes Términos de uso rigen la utilización que haga de nuestro servicio. Según se utilicen en estos Términos de uso, «el servicio de Netflix», «nuestro servicio» o «el servicio» se refieren al servicio personalizado brindado por Netflix para descubrir y acceder al contenido de Netflix, incluidas todas las características y funcionalidades, recomendaciones y críticas, nuestros sitios web y las interfaces de usuario, así como todo el contenido y software asociado a nuestro servicio. Las referencias a «usted» en estos Términos de uso señalan al miembro que creó la cuenta de Netflix y al que se le facturan los cargos a través de su forma de pago.</p>
      <b>1.Membresía</b>
      <p>1.1. Su membresía de Netflix continuará hasta que la cancele. Para usar el servicio de Netflix, debe tener acceso a internet y un dispositivo compatible con Netflix, y proporcionar una o más Formas de pago. «Forma de pago» significa una forma de pago actual, válida y aceptada, que pueda actualizarse periódicamente, y que pueda admitir pagos a través de su cuenta con terceros. A menos que cancele su membresía antes de la fecha de facturación, nos autoriza a cobrarle la cuota de membresía del siguiente ciclo de facturación a su Forma de pago (ver «Cancelación» a continuación).
     </p>
     <p>1.2. Podemos ofrecer una gran variedad de planes de membresía, incluidas las membresías que se ofrecen a través de terceros junto con la provisión de sus propios productos y servicios. No somos responsables por los productos y servicios provistos por dichos terceros. Ciertos planes de membresía pueden incluir diversas condiciones y limitaciones, las cuales se aclaran en el acuerdo de suscripción o en otras comunicaciones. Podrá encontrar la información específica sobre su membresía de Netflix visitando el sitio web netflix.com y haciendo clic en el vínculo «Cuenta», disponible en la parte superior de las páginas bajo su nombre de perfil.</p>
     <b>2.Ofertas promocionales</b>
     <p> Ocasionalmente, podríamos hacer ofertas especiales de promoción (como sorteos, descuentos y otros incentivos), planes o membresías («Ofertas»). Netflix determina los requisitos para acceder a la Oferta a su exclusivo criterio, y nos reservamos el derecho de revocar una Oferta y suspender su cuenta si determinamos que usted no es elegible. Los miembros de hogares con una membresía de Netflix existente o reciente podrían no ser elegibles para ciertas Ofertas introductorias. Podemos utilizar cierta información, como el Id. del dispositivo, la forma de pago o sus datos de contacto, para determinar la elegibilidad de la Oferta. Los requisitos de elegibilidad y otras limitaciones y condiciones se le informarán cuando se suscriba a la Oferta o en otras comunicaciones puestas a su disposición.</p>
     <b>3.Facturación y cancelación</b>
     <p>3.1. Ciclo de facturación. La cuota de membresía por el servicio de Netflix y cualquier otro cargo en el que incurra en relación con el uso que haga del servicio de Netflix, como los impuestos y las tarifas de cualquier posible transacción, se cobrarán mediante su Forma de pago en la fecha de pago específica indicada en la página «Cuenta». La duración de su ciclo de facturación dependerá del tipo de membresía que haya seleccionado al suscribirse al servicio. En ciertos casos, su fecha de pago podría cambiar, por ejemplo, si no se pudo hacer el cobro con su Forma de pago satisfactoriamente, cuando cambie su plan de membresía, o si su membresía pagada comenzó un día que no está incluido en un determinado mes. Visite el sitio web netflix.com y haga clic en la página «Cuenta» para ver su próxima fecha de pago. Podemos autorizar su Forma de pago antes del cobro de los cargos relacionados con la membresía o el servicio a través de varios métodos, e incluso autorizarla durante aproximadamente un mes de servicio desde su registro. Si se suscribió a Netflix usando su cuenta con un tercero como Forma de pago, puede encontrar la información sobre la facturación de su membresía de Netflix en su cuenta del servicio del tercero correspondiente.</p>
     <p>3.2. Formas de pago. Para usar el servicio de Netflix, debe proveer una o más Formas de pago. Nos autoriza a hacer cargos a cualquier Forma de pago asociada con su cuenta en caso de rechazo o indisponibilidad de su Forma de pago principal para cobrar el cargo de su membresía. Usted es responsable por cualquier cargo pendiente. Si el pago no se pudiera hacer satisfactoriamente, debido a la fecha de vencimiento, la falta de fondos u otros motivos, y si usted no cancela su cuenta, podemos suspender su acceso al servicio hasta que obtengamos una Forma de pago válida. Para algunas Formas de pago, el emisor puede cobrarle ciertos cargos, como cargos de transacción extranjera u otros cargos relacionados con el procesamiento de su Forma de pago. Los impuestos locales varían en función de la Forma de pago usada. Consulte con el proveedor de servicios de su Forma de pago para obtener información.
     </p>
     <p>3.3. Actualización de sus Formas de pago. Usted puede actualizar su Forma de pago en la página «Cuenta». También podemos actualizar su Forma de pago usando la información brindada por los proveedores de servicios de pago correspondientes. Luego de cualquier actualización, nos autoriza a emitir cargos a las Formas de pago correspondientes.</p>
     <p>3.4. Cancelación. Puede cancelar la membresía de Netflix en cualquier momento, y continuará teniendo acceso al servicio hasta el final de su periodo de facturación. En caso de que cancele su membresía voluntariamente (sin causa), los pagos no son reembolsables, y no se otorgarán reembolsos ni créditos por los periodos de membresía utilizados parcialmente o por el contenido de Netflix no usado. Para cancelar, visite la página «Cuenta» y siga las instrucciones de cancelación. Si cancela su membresía, su cuenta se cerrará automáticamente al final de su periodo de facturación actual. En la página «Cuenta», puede ver cuándo se cerrará su cuenta. Si se suscribió a Netflix usando su cuenta con un tercero como Forma de pago y desea cancelar su membresía de Netflix, es posible que tenga que hacerlo a través de dicho tercero, ya sea visitando su cuenta con el tercero correspondiente para desactivar su renovación automática o cancelando la membresía al servicio de Netflix a través de ese tercero.</p>
     <p>3.5. Cambios en el precio y en los planes de membresía. Podemos cambiar nuestros planes de membresía y el precio de nuestro servicio de vez en cuando. Le informaremos los cambios en el precio del servicio o en sus planes de membresía con al menos un mes de anticipación a la fecha de entrada en vigencia. Si no desea aceptar el cambio de precio o la modificación del plan, puede cancelar su membresía antes de que el cambio entre en vigor.</p>
     <b>4.Servicio de Netflix</b>
     <p>4.1. Usted debe tener al menos 18 años para ser miembro del servicio de Netflix. Los menores solamente pueden usar el servicio bajo la supervisión de un adulto.</p>
     <p>4.2. El servicio de Netflix y todo el contenido al que se accede en él son solo para uso personal, no comercial, y no deben compartirse con otras personas que no sean miembros de su hogar, a menos que su plan de membresía lo permita. Durante su membresía de Netflix, le otorgamos un derecho limitado, no exclusivo e intransferible para acceder al servicio y al contenido de Netflix. Más allá de esto, no se le transferirá ningún otro derecho, título o interés. Usted acepta que no usará el servicio para presentaciones públicas.</p>
     <p>4.3. Usted puede acceder al contenido de Netflix principalmente en el país donde estableció su cuenta y solo en los lugares geográficos en los que ofrecemos nuestro servicio y donde se tenga licencia para ese contenido. El contenido disponible puede variar según la ubicación geográfica y cambiar periódicamente. La cantidad de dispositivos en los que puede ver simultáneamente depende del plan de membresía elegido y se especifica en la página «Cuenta».
     </p>
     <p>4.4. El servicio de Netflix, inclusive su contenido, se actualiza regularmente. Por lo tanto, no garantizamos que un contenido particular esté disponible en el servicio de Netflix en un momento determinado. Podemos ofrecerle la oportunidad de ver eventos en vivo o eventos especiales (incluso la repetición de dicho contenido) o de disfrutar de nuevas funciones adicionales. Dicho contenido y las nuevas funciones pueden incluir pausas comerciales y otros tipos de mensajes y formatos publicitarios («Anuncios»). Nuestro servicio también puede incluir contenido comercial limitado, como contenido de marca o mensajes de patrocinio, videos promocionales del contenido de Netflix o información relacionada con otros bienes o servicios de Netflix. Netflix no avala ni patrocina ningún producto o servicio anunciado, y cualquier interacción con los anunciantes, incluso a través de la interacción con anuncios interactivos, es por elección suya y a su propio riesgo. Además, probamos regularmente varios aspectos de nuestro servicio, tales como nuestros sitios web, las interfaces de usuario y las funciones promocionales. Usted puede desactivar en cualquier momento su participación en pruebas visitando la página «Cuenta» y cambiando la configuración de «Participación en pruebas».</p>
     <p>4.5. Parte del contenido de Netflix está disponible para la descarga temporal y para ver offline en ciertos dispositivos compatibles («Títulos offline»). Se aplican restricciones, incluidas las restricciones a la cantidad de Títulos offline por cada cuenta, la cantidad máxima de dispositivos que pueden contener Títulos offline, el periodo en el cual deberá comenzar a ver los Títulos offline y cuánto tiempo permanecerán accesibles los Títulos offline. Es posible que algunos Títulos offline no se puedan reproducir en determinados países y que, si se conecta en un país en el que no se puede hacer streaming de ese Título offline, dicho título no se pueda reproducir mientras esté en ese país.</p>
     <p>4.6. Usted acepta usar el servicio de Netflix, incluidas todas las características y funcionalidades asociadas con este, conforme a lo establecido en todas las leyes, normas y reglamentaciones vigentes, o cualquier otra restricción al uso del servicio o su contenido. Excepto por lo expresamente autorizado por nosotros, usted acepta no:
    </p>
     <p>(i) archivar, reproducir, distribuir, modificar, mostrar, ejecutar, publicar, otorgar licencias, crear obras derivadas basadas en el servicio, ofrecer en venta, o usar contenido e información incluida en el servicio de Netflix u obtenida a través de este;

(ii) evitar, eliminar, alterar, desactivar, degradar, bloquear, ocultar, modificar o burlar las protecciones de contenido u otros elementos del servicio de Netflix, incluida la interfaz gráfica del usuario, los anuncios publicitarios o las funciones publicitarias, los avisos de derechos de autor y las marcas registradas;

(iii) usar algún robot, spider, scraper u otra forma automatizada para acceder al servicio de Netflix;

(iv) descompilar, realizar ingeniería inversa, desarmar cualquier software u otro producto o proceso a los que se acceda a través del servicio de Netflix;

(v) introducir un código o producto o manipular el contenido del servicio de Netflix de alguna manera;

(vi) usar método alguno de minería de datos, extracción u obtención de datos;

(vii) subir, publicar, enviar por email ni enviar o transmitir de cualquier otra forma ningún material diseñado para interrumpir, destruir o limitar la funcionalidad del software de computación, hardware o equipos de telecomunicaciones asociados con el servicio de Netflix, incluido material que contenga virus de software o cualquier otro código informático, archivos o programas; o

(viii) realizar cualquiera de las prácticas mencionadas con respecto al uso, creación, desarrollo, modificación, activación, ajuste, capacitación, testeo, análisis comparativo o validación de cualquier herramienta de aprendizaje automático, modelo, sistema, algoritmo, producto u otra tecnología.

Podríamos cancelar o restringir su uso de nuestro servicio si usted viola cualquiera de estos Términos de uso o usa el servicio de forma ilegal o fraudulenta.</p>
     
     <p>4.7. La calidad de la imagen del contenido de Netflix puede variar según el dispositivo y puede verse afectada por diversos factores, tales como la ubicación, el ancho de banda disponible o la velocidad de la conexión a internet. La disponibilidad del contenido en alta definición (HD), ultra alta definición (Ultra HD) y alto rango dinámico (HDR) depende de su servicio de internet y del dispositivo en uso. La calidad del audio espacial depende del dispositivo en uso. No todo el contenido está disponible en audio espacial o en todos los formatos, como HD, Ultra HD o HDR, ni todos los planes de membresía le permiten recibir contenido en todos los formatos. La velocidad de conexión mínima para obtener una calidad de video HD (definida como una resolución de 720p o superior) es de 3.0 Mb/s por stream. Sin embargo, recomendamos una conexión más rápida para mejorar la calidad de video. Se recomienda una velocidad de conexión de, al menos, 5.0 Mb/s por stream para recibir contenido con calidad de video Full HD (definida como una resolución de 1080p o superior). Se recomienda una velocidad de conexión de, al menos, 15.0 Mb/s por stream para recibir contenido con calidad de video Ultra HD (definida como una resolución de 4K o superior). Todos los cargos de acceso a internet correrán por su cuenta. Solicite a su proveedor de internet información acerca de los posibles cargos de consumo de datos por uso de internet. El tiempo que lleva comenzar a ver contenido de Netflix variará según diversos factores, incluidos su ubicación, el ancho de banda disponible en ese momento, el contenido que haya seleccionado y la configuración de su dispositivo compatible con Netflix.</p>   
     <p>4.8. El software de Netflix es desarrollado por Netflix o para Netflix, y solamente puede ser utilizado para el streaming autorizado y para acceder al contenido de Netflix a través de dispositivos compatibles con Netflix. Este software puede variar según el dispositivo y el medio, y las funcionalidades y las características también pueden variar de un dispositivo a otro. Usted reconoce que el uso del servicio puede requerir software de terceros que esté sujeto a licencias de terceros. Usted acepta que puede recibir automáticamente versiones actualizadas del software de Netflix y el software relacionado de terceros.</p>
     <b>5.Contraseñas y acceso a la cuenta. </b>
     <p>Usted es responsable de cualquier actividad que ocurra en su cuenta de Netflix. Al permitir que otras personas accedan a la cuenta (lo que incluye el acceso a la información sobre la actividad de visualización de la cuenta), usted acepta que dichas personas actúan en su nombre y que tendrá que aceptar cualquier cambio que puedan realizar en la cuenta, incluidos, entre otros, los cambios en el plan de membresía. Para ayudar a mantener el control sobre la cuenta y evitar que cualquier usuario no autorizado acceda a esta, debe mantener el control sobre los dispositivos que se utilizan para acceder al servicio, y no revelar a nadie la contraseña o los detalles de la Forma de pago asociada a la cuenta. Usted se compromete a proporcionar y mantener información precisa en relación con su cuenta, incluidos datos de contacto válidos para que podamos enviarle notificaciones acerca de su cuenta. Podemos cancelar o suspender su cuenta para protegerlo a usted, a Netflix o a nuestros socios contra el robo de identidad u otra actividad fraudulenta.</p>
     <b>6.Disposiciones varias</b>
     <p>6.1. Material no solicitado. Netflix no acepta materiales ni ideas no solicitados para su contenido, y no es responsable por la similitud entre los contenidos o la programación de cualquier medio con los materiales o ideas transmitidos a Netflix.</p>
     <p>6.2. Servicio al Cliente.Si necesita obtener más información sobre nuestro servicio y sus características, o si necesita asistencia con su cuenta, visite el Centro de ayuda de Netflix, al que puede acceder a través del sitio web netflix.com. En algunos casos, el Servicio al Cliente podrá ayudarlo mejor utilizando una herramienta de asistencia de acceso remoto con la que se ingresa completamente a su computadora. Si no desea que tengamos este acceso, usted no debería autorizar la asistencia a través de la herramienta de acceso remoto, y nosotros le ayudaremos de otra forma. En el caso de que haya un conflicto entre estos Términos de uso y la información proporcionada por el Servicio al Cliente u otras secciones de nuestros sitios web, estos Términos de uso serán los que regirán.</p>
     <p>6.3. Vigencia. Si alguna de las disposiciones de estos Términos de uso es declarada nula, ilegal o inaplicable, la validez, legalidad y aplicación de las restantes disposiciones continuarán en plena vigencia.</p>
     <p>6.4. Cambios en los Términos de uso y cesión. Netflix puede cambiar estos Términos de uso cuando sea necesario. En caso de introducirse cambios materiales, le informaremos con al menos un mes de anticipación a que dichos cambios le sean aplicables. Si no desea aceptar los cambios, puede cancelar su membresía antes de que estos entren en vigor. Podemos ceder o transferir nuestro acuerdo con usted, incluidos nuestros derechos y obligaciones asociados, en cualquier momento y usted acepta cooperar con nosotros en relación con dicha cesión o transferencia.</p>
     <p>6.5. Eventos más allá de nuestro control razonable. Es posible que el servicio o el contenido de Netflix no esté disponible o que no pueda descargarse en cualquier momento como resultado de eventos más allá de nuestro control razonable, incluidos, entre otros: (i) interrupciones de energía o de los servidores; (ii) cualquier tipo de actos o errores de terceros, como proveedores de red; (iii) guerras, disturbios, huelgas o malestar social; o (iv) cualquier otro evento o factor fuera de nuestro control razonable. Si bien haremos lo posible para notificarle con anticipación, en tanto lo permita la ley aplicable, no seremos responsables en caso de que esos eventos ocurran.</p>
     <p>6.6. Comunicaciones electrónicas. Le enviaremos la información relativa a su cuenta (por ejemplo, las autorizaciones de pago, las facturas, los cambios de contraseña o de la Forma de pago, los mensajes de confirmación, los avisos) de manera electrónica únicamente.</p>
     <br />
     <p>Última actualización: 17 de abril de 2025</p>
     
     
     
     </div>
     </>
  )
}

export default TerminosDeUso
